# Generated by Django 6.0.1 on 2026-08-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='producto',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
